# Generated by Django 3.1.6 on 2021-02-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20210219_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='user',
        ),
    ]
